inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

# @TODO: import.rb

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - '**/*.rake'
    - 'app/helpers/form_input_helper.rb'
    - 'app/models/import.rb'
    - 'app/models/document/date_range_validator.rb'
    - 'app/models/document/bbox_validator.rb'

Layout/ExtraSpacing:
  Exclude:
    - '**/*.jbuilder'

Layout/LineLength:
  Enabled: true
  Exclude:
    - '**/*.rake'
    - '**/*.jbuilder'
    - 'app/helpers/application_helper.rb'
    - 'app/jobs/export_job.rb'
    - 'app/jobs/export_json_job.rb'
    - 'app/controllers/reports_controller.rb'
  Max: 140

Lint/AssignmentInCondition:
  Exclude:
    - 'app/channels/application_cable/connection.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/jobs/export_job.rb'
    - 'app/jobs/export_json_job.rb'
    - 'app/models/document/solr_geom_validator.rb'
    - 'app/models/report.rb'
    - 'app/controllers/reports_controller.rb'
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'app/indexers/document_indexer.rb'
    - 'app/jobs/export_json_job.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/document.rb'
    - 'app/controllers/documents_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/documents_controller.rb'
    - 'app/controllers/reports_controller.rb'
    - 'app/helpers/reports_helper.rb'
    - 'app/models/report.rb'
    - 'app/jobs/import_run_job.rb'
    - 'app/jobs/export_job.rb'
    - 'app/jobs/export_json_job.rb'
    - 'app/models/document/solr_geom_validator.rb'
    - 'app/models/import_btaa_aardvark.rb'
    - 'app/services/export_csv_service.rb'
    - 'app/services/export_json_service.rb'
  Max: 16

Metrics/ParameterLists:
  Exclude:
    - 'app/models/blacklight_api.rb'

Naming/MethodName:
  Exclude:
    - 'app/models/document.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/document_access.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/bulk_action_transition.rb'
    - 'app/models/bulk_action_document_transition.rb'
    - 'app/models/document_transition.rb'
    - 'app/models/import.rb'
    - 'app/models/import_transition.rb'
    - 'app/models/import_document_transition.rb'
