url: https://archive.apache.org/dist/lucene/solr/8.11.1/solr-8.11.1.zip
validate: false
instance_dir: tmp/solr
download_dir: tmp/solr
collection:
  dir: solr/conf/
  name: blacklight-core
  persist: true
